// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealtimeStockEntityFramework.Models;

namespace RealtimeStockEntityFramework.Migrations
{
    [DbContext(typeof(RealtimeStockContext))]
    partial class RealtimeStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealtimeStockEntityFramework.Models.RealtimeStock", b =>
                {
                    b.Property<Guid>("RealtimeStockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeTraded")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(20, 10)");

                    b.HasKey("RealtimeStockId");

                    b.ToTable("RealtimeStock");
                });
#pragma warning restore 612, 618
        }
    }
}
