// <auto-generated />
using System;
using CompaniesEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompaniesEntityFramework.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20210114134153_RemovedCurrencySymbol")]
    partial class RemovedCurrencySymbol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompaniesEntityFramework.Models.CompanyInformation", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Ipo")
                        .HasColumnType("date");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("MarketCapitalization")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<float>("OutstandingShares")
                        .HasColumnType("real");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("CompanyId")
                        .HasName("CompanyInformation_pk");

                    b.HasIndex("SymbolId");

                    b.ToTable("CompanyInformation");
                });

            modelBuilder.Entity("CompaniesEntityFramework.Models.CompanySymbol", b =>
                {
                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("SymbolId")
                        .HasName("CompanySymbol_pk");

                    b.ToTable("CompanySymbol");
                });

            modelBuilder.Entity("CompaniesEntityFramework.Models.CompanyInformation", b =>
                {
                    b.HasOne("CompaniesEntityFramework.Models.CompanySymbol", "Symbol")
                        .WithMany("CompanyInformation")
                        .HasForeignKey("SymbolId")
                        .HasConstraintName("CompanySymbol_CompanyInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
